### ISSUE TITLE
Bug: Comma with whitespaces leads to error

### ISSUE THREAD

**Issue by olafthiele** [oliverguhr/deepmultilingualpunctuation#1]
Great lib, found this small bug:

```python
text = "das , ist fies "
```

leads to error

`TypeError: unsupported operand type(s) for +: 'int' and 'str'`

when converting the results to text.

**Comment by oliverguhr** [comment]
This is a nasty bug. Apparently, the label can be a string or like in this case a number.

**Comment by oliverguhr** [comment]
Published the fix. You can test it by upgrading to 1.0.1 

Feel free to reopen the issue if needed.
