### ISSUE TITLE
User Warning , grouped_entities=False

### ISSUE THREAD

**Issue by leinaxd** [oliverguhr/deepmultilingualpunctuation#10]
I followed your tutorial and works great!
however i get the following Warning coming from **hugging face pipeline**:

```
/usr/local/lib/python3.8/dist-packages/transformers/pipelines/token_classification.py:159: UserWarning: `grouped_entities` is deprecated and will be removed in version v5.0.0, defaulted to `aggregation_strategy="none"` instead.
  warnings.warn(
```

Here is the required doc:
[Hugging Face pipeline](https://huggingface.co/docs/transformers/main_classes/pipelines#transformers.TokenClassificationPipeline)

And the line of code to change is:
From the **PunctuationModel** (inside the **\_\_init\_\_** method...) both **pipeline()** calls

Would you consider updating those lines in order to get rid of the warning?
Thank you in advance!

**Comment by oliverguhr** [comment]
Thanks for the PR @leinaxd. I will merge this as soon as I tested it.
