### ISSUE TITLE
finetune tune the model

### ISSUE THREAD

**Issue by Body123** [oliverguhr/deepmultilingualpunctuation#11]
How can I finetune the model in other language on custom dataset is there a code exmple?

**Comment by oliverguhr** [comment]
Hi @Body123 
Yes you can! For complete code of the reareach project take a look at [this repository](https://github.com/oliverguhr/fullstop-deep-punctuation-prediction).

There is also an guide on [how to fine tune this model for you data / language](https://github.com/oliverguhr/fullstop-deep-punctuation-prediction/blob/main/other_languages/readme.md).
