### ISSUE TITLE
Load local model for offline usage?

### ISSUE THREAD

**Issue by ZQ-Dev8** [oliverguhr/deepmultilingualpunctuation#13]
Hi Oliver, thank you for this awesome contribution.

One question - how can we direct the library to load a model that is stored locally, as opposed to downloading from HuggingFace? This would be extremely helpful with offline or air-gapped usage of your library.

Thank you!

**Comment by oliverguhr** [comment]
Hi @dcruiz01,
I never tested offline usage, but it should work out of the box. 
You need to download the model from [here](https://huggingface.co/oliverguhr/german-sentiment-bert/tree/main) into a folder on your disk. Then simply pass the path to the "model" argument like so:

```
model = PunctuationModel(model = "path/to/your/folder")
```

Let me know if this works for you.

**Comment by rajkanani** [comment]
[oliverguhr](https://github.com/oliverguhr) did you do the test offline?

btw it's working

**Comment by oliverguhr** [comment]
@rajkanani I did not test this, as this is a feature of the transformers library. But it should work :)
