### ISSUE TITLE
Could you give PunctuationModel a init arg for config pipeline?

### ISSUE THREAD

**Issue by kaka1909** [oliverguhr/deepmultilingualpunctuation#16]
Firstly, many thanks for your awesome project which can help me do nice punctuation, but for transformer pipeline, I hope I can pass in some config to make it works as I expected, for e.g I wanna config local_files_only and cache_dir, but no place to config. Thanks in advance.

**Comment by oliverguhr** [comment]
Oh, sorry for the late reply. You can just download the repo from huggingface and point to the directory like this:

`model = PunctuationModel(model = "path/to/local/model")`

**Comment by oliverguhr** [comment]
PS: Feel free to reopen this if needed
