### ISSUE TITLE
Can you improve it for SRT subtitle file?

### ISSUE THREAD

**Issue by bk111** [oliverguhr/deepmultilingualpunctuation#17]
Can you improve it for SRT subtitle file?

the SRT subtitle format like this:
1
00:00:00,000 --> 00:00:04,000
Guess how much I love you

2
00:00:04,000 --> 00:00:11,000
One autumn morning little nut-brown hair big nut-brown hair and little field mouse

3
00:00:11,000 --> 00:00:18,000
sat bathed in the early morning light fascinated by one of Little White Owl's stories

**Comment by oliverguhr** [comment]
Ask ChatGPT to write you a python script that reads SRT files and uses the [pip package](https://github.com/oliverguhr/deepmultilingualpunctuation?tab=readme-ov-file#restore-punctuation) to add punctuation.
