### ISSUE TITLE
unsupported operand type(s) for +: 'int' and 'str'

### ISSUE THREAD

**Issue by shivam-kumar123** [oliverguhr/deepmultilingualpunctuation#18]
result = punctuation_model.restore_punctuation(some_text)
the above line when executed gives this issue 
unsupported operand type(s) for +: 'int' and 'str'

I have made sure that the text in some_text veriable is string

python code 
from deepmultilingualpunctuation import PunctuationModel
punctuation_model = PunctuationModel()
result = punctuation_model.restore_punctuation(some_text)

earlier this code used to work , now it doesn't , pls help

**Comment by shivam-kumar123** [comment]
there is not such issue , I am getting this error 
unsupported operand type(s) for +: 'int' and 'str'
because of the text that the model processed , any tips on how to pre-process the text before feeding it to the model

**Comment by oliverguhr** [comment]
Can you provide a colab notebook to reproduce this issue?

**Comment by shivam-kumar123** [comment]
I had used PyMuPDF library in python to extract text from pdf files , and then I was passing it to the model , the probem occured when I have images in my pdf. I will make sure to provide you notebook shortly

**Comment by oliverguhr** [comment]
I close this ticket for now. Feel free to reopen it if this issue persists.
