### ISSUE TITLE
Is there a way to use a downloaded model?

### ISSUE THREAD

**Issue by tarasowski** [oliverguhr/deepmultilingualpunctuation#19]
I want to deploy it to AWS Lambda, and it works so far, but it downloads the model each time, which takes a lot of time.

**Comment by oliverguhr** [comment]
Yes, this should be possible.

1. Clone the models repository from [here](https://huggingface.co/oliverguhr/fullstop-punctuation-multilang-large/tree/main?clone=true)
2.    Create a new class instance with the path to the cloned repository
```model = PunctuationModel(model = "/path/to/repo/folder")```

**Comment by tarasowski** [comment]
Thanks Oliver! Actually did that and it works.
The only downside I can't get it running on Lamda. The local model doesn't get loaded somehow.

**Comment by oliverguhr** [comment]
Thanks for the feedback! Unfortunately, since I do not use AWS lambda, I can't help you with that issue.

**Comment by oliverguhr** [comment]
Feel free to post a solution if you solve this issue.
