### ISSUE TITLE
Support for other languages ?

### ISSUE THREAD

**Issue by FordSoft** [oliverguhr/deepmultilingualpunctuation#2]
Hello, can this model be trained to support other languages (Russian)? If so, how can I do this, I would be grateful if you tell me. Thanks!

**Comment by oliverguhr** [comment]
Yes this is possible. I explained it in this issue briefly 

https://github.com/oliverguhr/fullstop-deep-punctuation-prediction/issues/5#issuecomment-1073885665

**Comment by FordSoft** [comment]
Thanks! let's try.

**Comment by jordimas** [comment]
This may be useful: https://github.com/oliverguhr/fullstop-deep-punctuation-prediction/pull/7/files
