### ISSUE TITLE
More languages

### ISSUE THREAD

**Issue by orlink** [oliverguhr/deepmultilingualpunctuation#3]
A fantastic model! Thank you for sharing it on huggingface. Is it possible to upload also a model based on xml-roberta-base trained on all the languages in the Europarl data set? I have noticed it generalizes well to other languages for some of the more difficult cases, such commas at the end of subordinate clauses, but it misses some cases where the comma is always or almost always present in some languages. For example in Bulgarian: "Отивам на село, защото искам да си почина."; "Той каза, че ще дойде по-късно"; "Мислех си кой може да свърши работата с моя помощ и се сетих, че имам един приятел, който е съдружник във фирма, която прави подобни неща."
Is it going to worsen signficantly the performance for English?

**Comment by orlink** [comment]
I just found out the instructions for training for other languages. I'm a bit new to this.

**Comment by oliverguhr** [comment]
Hi @orlink,
very good question. I think we have to train an actual model to find this out. My guess is, that this would work. XLM-Roberta was trained in 100 languages and at least the large model should have enough capacity to solve this task.

**Comment by orlink** [comment]
Hi, Oliver, I fine-tuned the base model on 23 languages from europarl. It seems to work pretty good for all.

**Comment by oliverguhr** [comment]
Hi Orlin,
that sounds great! Do you plan to share your model?

**Comment by orlink** [comment]
Hi Oliver, I have shared the one that I trained on 12 languages, including English and Bulgarian at https://huggingface.co/kredor/punctuate-all. The one I trained on 23 languages I still haven't shared. It turned out huggingface was too expensive and somewhat slow for inference, so I hosted it on a Google Cloud n2-standard-4 Intel Ice Lake preemtible instance with a cron job to restart it.  It took some googling and experimentation to figure it out.  Inference time is about 40 ms.  I also needed another NER model which I also hosted there.

**Comment by oliverguhr** [comment]
Hi @orlink,
thats interesting, I expected huggingface to have some clever tricks to improve the inference performance. Did you use quantitation to optimize your model for inference?

I finally linked your model in the model card of my models and the [github repository](https://github.com/oliverguhr/deepmultilingualpunctuation#languages). Your model will be helpful for a lot of people, thanks again for contributing!

Best
Oliver

**Comment by orlink** [comment]
Hi @oliverguhr 
The speedup is, I believe, due to the fact that I'm using two core Ice Lake CPU and Hangingface, I guess, is giving it only one core. When I use only one core, I get the same time as huggingface - about 65ms. Also when I send two requests at the same time. There must be some parallel processing going on in the pipeline or model. At which step do you think it is?

**Comment by oliverguhr** [comment]
Pytorch does that - during inference it spreads the matrix multiplications across the cores of your CPU. You can also use 4 or more cores - pytorch handels that for you.
