### ISSUE TITLE
Error: “Chunk size too large, text got clipped” 

### ISSUE THREAD

**Issue by phyllisgraf** [oliverguhr/deepmultilingualpunctuation#4]
Hello : )

First of all, thank you for your work! We are currently using it for a group project at university and it’s super helpful.

There is just one small issue: When we are using the _restore_punctuation_ function on a large enumeration that is missing commas, we get a “Chunk size too large, text got clipped” error as shown below:

![Error](https://user-images.githubusercontent.com/43384655/170429350-9c9ac35f-f34d-48fd-a5d2-c86b7da0df7b.jpeg)

We can't seem to find a solution. Do you have any idea how to fix this?
Thanks in advance!

Phyllis

In case you want to replicate the error, this is the text snipped we are using:
“This is a list: Diindolylmethane (DIM) Dimethylaminoethanol (DMAE) Dong Quai Echinacea Eclipta Alba Egg Shell Calcium Elderberry Eleutherosides Emblica Essential Fatty Acids Energy EDTA Eurycoma Longifolia Evodia Extract Eye Health Ferulic Acid Fish Oils GABA Gamma Tocopherol Garlic Ginger Extract Ginkgo Biloba Ginseng Glucosamine Glutathione Goji Berry Gotu Kola GPC Choline Grape Seed Extract Green Coffee Bean Green Tea Gymnema Sylvestre Health Commentaries Health Questionnaires Heart Attacks Heart Health Herbs Hormone Support Huperzine Immune System Support Inflammation Joint Pain Kohki Tea L-Arginine L-Citrulline L-Cysteine L-Theanine L-Tyrosine Licorice Extract Life Extension Lipoic Acid Liver Support Longevity and Anti-Aging Lutein Luteolin Lycium Berry Lycopene Lysine Magnesium Magnolia Malic Acid Mastic Gum Medium-Chain Triglycerides Melatonin Memory Menopause Menaquinone-7 Men's Health Mental Health Metabolic Syndrome Minerals Mixed Tocopherols Multi-Vitamins Myricetin N-Acetyl Cysteine (NAC) N-Acetyl-carnosine Naringenin Nattokinase Nettle Notoginseng Nutrition Olive Leaf Oolong Tea Omega-3 Fatty Acids OKG Ornithine Oral Chelation Oral Health - Teeth and Gums Osteoporosis Overall Health Pain Relief Parkinson's Disease Passionflower Peony Persimmon Phenylalanine Pheromones Phosphatidylserine Phytosterol Pine Bark Policosanol Pomegranate Pregnenolone Probiotics Prostate Health Pueraria Mirifica Pumpkin Pygeum Africanum R-Lipoic Acid Red Wine Resveratrol Rhodiola Rosea Rosemary Salacia Reticulata Salvia Miltiorrhiza Schisandra Berry Selenium Sexual Health Silymarin Skin Hair and Nails Sleep Soy Phytosterol St John's Wort Stinging Nettle Stress Strontium Citrate Suntheanine Taurine Terminalia Chebula The Common Cold Turmeric Root Tyrosine Uridine Urinary Tract Health Urtica Dioica Root Varicose Veins Vinpocetine Vision Health"

**Comment by Bilal4801** [comment]
you should write the code that split your text (you can use regex for that)  that passes the model that may solve your problem.

**Comment by oliverguhr** [comment]
@phyllisgraf Sorry for the late response.  This problem is, that you have a lot of uncommon words with number in them. These texts create a lot of tokens which leads to an overflow - this causes the "chunk_size to large" error.

You can try to solve this issue if you:

1. Copy the code of [this class](https://github.com/oliverguhr/deepmultilingualpunctuation/blob/main/deepmultilingualpunctuation/punctuationmodel.py) to your code.
2. Reduce the "chunk_size" [in this line ](https://github.com/oliverguhr/deepmultilingualpunctuation/blob/main/deepmultilingualpunctuation/punctuationmodel.py#L31) until the error disappears. Lets say you set it so 100, if the error occurs again, set it to 80 .. and so on.
