### ISSUE TITLE
More punctuation options

### ISSUE THREAD

**Issue by Bilal4801** [oliverguhr/deepmultilingualpunctuation#5]
Good work Oliverguhr..... 
you should add more punctuation options to the model and train the model on other domains of the text.

**Comment by oliverguhr** [comment]
Thanks @Bilal4801 

We wrote a tutorial on how to train a model for other texts and languages - so feel free to add more :) 

Currently, we are working on a dutch mono and multilingual version.

**Comment by robotsp** [comment]
> Thanks @Bilal4801
> 
> We wrote a tutorial on how to train a model for other texts and languages - so feel free to add more :)
> 
> Currently, we are working on a dutch mono and multilingual version.

Where can I get the tutorial ? I want to train a Japanese version. Thanks!

**Comment by oliverguhr** [comment]
@robotsp You can find the tutorial here: https://github.com/oliverguhr/fullstop-deep-punctuation-prediction/blob/main/other_languages/readme.md

**Comment by dgoryeo** [comment]
> to train a Ja

Hi @robotsp , just came across this thread. Did you ever manage to train a Japanese version for this? I am looking for a Japanese punctiation model Thanks
