### ISSUE TITLE
predict() labels each individual character instead of whole word

### ISSUE THREAD

**Issue by ghost** [oliverguhr/deepmultilingualpunctuation#7]
Code
    model = PunctuationModel()
    labled_words = model.predict(data)

Expected output: (something like this)
    [['My', '0', 0.9999887], ['name', '0', 0.99998665], ['is', '0', 0.9998579], ['Clara', '0', 0.6752215], ['and', '0', 0.99990904], ['I', '0', 0.9999877], ['live', '0', 0.9999839], ['in', '0', 0.9999515], ['Berkeley', ',', 0.99800044], ['California', '.', 0.99534047], ['Ist', '0', 0.99998784], ['das', '0', 0.99999154], ['eine', '0', 0.9999918], ['Frage', ',', 0.99622655], ['Frau', '0', 0.9999889], ['Müller', '?', 0.99863917]]

Actual Outpu: (like this)
    [['S', '0', 0.85909706], ['p', '0', 0.79623544], ['i', '0', 0.97123384], ['d', '0', 0.9573735], ['e', '0', 0.7520275], ['r', '0', 0.83077455], ['-', '0', 0.912434], ['M', '0', 0.79773486], ['a', '0', 0.8560487], ['n', '0', 0.80509317], [' ', 0, 0.80509317], ['i', '0', 0.9247775], ['s', '0', 0.93199074], [' ', 0, 0.93199074], ['a', '0', 0.93133676]]

**Comment by ghost** [comment]
Works as expected when

labled_words = model.predict(data.split()]

**Comment by oliverguhr** [comment]
Just make shure you verify the results. The model was not trained for this - so it could be that the results are wrong.
