### ISSUE TITLE
how do you use tensorflow gpu with this ?

### ISSUE THREAD

**Issue by skintflickz** [oliverguhr/deepmultilingualpunctuation#8]
Is it possible to utilise a gpu when processing text with this script ?
I have it working fine but it uses my CPU and I have very large chunks of text I want to process and it take to long with just the cpu.

**Comment by skintflickz** [comment]
Beofre anyone asks .. yes my other scripts use the gpu I have k80

**Comment by oliverguhr** [comment]
Hi @skintflickz,

the code checks if a gpu is available and uses it automatically. But the code uses torch. So you need to install the current gpu version of torch to run this package. 


You can check your environment with:

import torch
torch.cuda.is_available()

**Comment by skintflickz** [comment]
I thought it uses tensorflow
Doh
